# Atividade 2 — Exercícios de Limpeza, Transformação e Agrupamento de Dados

Responda as perguntas abaixo usando o dataset **emendas_tratamento.parquet**. o dataset pode ser baixado em https://drive.google.com/file/d/19ydA23-eboyiKxN29JL1EQWW4CplTiKg/view?usp=sharing.

Cada resposta deve ter:
- Uma célula de **código** com a solução
- Uma célula de **texto** (Markdown) com a sua interpretação do resultado

---
## Passo 0 — Importar pandas e carregar os dados

In [2]:
import pandas as pd
df= pd.read_parquet('/content/emendas_parlamentares (1) (1).parquet')
df.head()

FileNotFoundError: [Errno 2] No such file or directory: '/content/emendas_parlamentares (1) (1).parquet'

## 1) Filtre apenas as emendas do ano de **2022** e mostre as 30 primeiras linhas. Em seguida responda: Quanta emendas foram registradas em 2022?

In [ ]:
df_2022 = df[df['Ano da Emenda'] == 2022]
display(df_2022.head(30))
num_emendas_2022 = len(df_2022)
print(f"Foram registradas {num_emendas_2022} emendas em 2022.")

,Código da Emenda,Ano da Emenda,Tipo de Emenda,Código do Autor da Emenda,Nome do Autor da Emenda,Número da emenda,Localidade de aplicação do recurso,Código Município IBGE,Município,Código UF IBGE,...,Nome Ação,Código Plano Orçamentário,Nome Plano Orçamentário,Valor Empenhado,Valor Liquidado,Valor Pago,Valor Restos A Pagar Inscritos,Valor Restos A Pagar Cancelados,Valor Restos A Pagar Pagos,Código da Emenda_1
63473,202238950001,2022,Emenda Individual - Transferências Especiais,3895.0,ABILIO SANTANA,1,CONCEIÇÃO DO ALMEIDA - BA,2908309,CONCEIÇÃO DO ALMEIDA,2900000,...,TRANSFERENCIAS ESPECIAIS,0,TRANSFERENCIAS ESPECIAIS,500000.00,0.00,0.00,500000.00,0.0,500000.00,202238950001
63474,202238950002,2022,Emenda Individual - Transferências com Finalid...,3895.0,ABILIO SANTANA,2,CONCEIÇÃO DO ALMEIDA - BA,2908309,CONCEIÇÃO DO ALMEIDA,2900000,...,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,0,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,750141.00,750141.00,750141.00,0.00,0.0,0.00,202238950002
63475,202238950003,2022,Emenda Individual - Transferências Especiais,3895.0,ABILIO SANTANA,3,CRUZ DAS ALMAS - BA,2909802,CRUZ DAS ALMAS,2900000,...,TRANSFERENCIAS ESPECIAIS,0,TRANSFERENCIAS ESPECIAIS,500000.00,0.00,0.00,500000.00,0.0,500000.00,202238950003
63476,202238950004,2022,Emenda Individual - Transferências Especiais,3895.0,ABILIO SANTANA,4,IRAMAIA - BA,2914307,IRAMAIA,2900000,...,TRANSFERENCIAS ESPECIAIS,0,TRANSFERENCIAS ESPECIAIS,200000.00,0.00,0.00,200000.00,0.0,200000.00,202238950004
63477,202238950005,2022,Emenda Individual - Transferências Especiais,3895.0,ABILIO SANTANA,5,MUCURI - BA,2922003,MUCURI,2900000,...,TRANSFERENCIAS ESPECIAIS,0,TRANSFERENCIAS ESPECIAIS,500000.00,0.00,0.00,500000.00,0.0,500000.00,202238950005
63478,202238950006,2022,Emenda Individual - Transferências com Finalid...,3895.0,ABILIO SANTANA,6,SERRA DO RAMALHO - BA,2930154,SERRA DO RAMALHO,2900000,...,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,0,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,535815.00,535815.00,535815.00,0.00,0.0,0.00,202238950006
63479,202238950007,2022,Emenda Individual - Transferências Especiais,3895.0,ABILIO SANTANA,7,SOUTO SOARES - BA,2930808,SOUTO SOARES,2900000,...,TRANSFERENCIAS ESPECIAIS,0,TRANSFERENCIAS ESPECIAIS,200000.00,0.00,0.00,200000.00,0.0,200000.00,202238950007
63480,202238950008,2022,Emenda Individual - Transferências com Finalid...,3895.0,ABILIO SANTANA,8,MÚLTIPLO,Sem informação,Múltiplo,2900000,...,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,0,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,470837.00,470837.00,470837.00,0.00,0.0,0.00,202238950008
63481,202238950009,2022,Emenda Individual - Transferências Especiais,3895.0,ABILIO SANTANA,9,MÚLTIPLO,Sem informação,Múltiplo,2900000,...,TRANSFERENCIAS ESPECIAIS,0,TRANSFERENCIAS ESPECIAIS,1100000.00,0.00,0.00,1100000.00,0.0,1100000.00,202238950009
63482,202238950010,2022,Emenda Individual - Transferências com Finalid...,3895.0,ABILIO SANTANA,10,MÚLTIPLO,Sem informação,Múltiplo,2900000,...,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,0,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,8573048.00,8123048.00,8123048.00,450000.00,0.0,450000.00,202238950010
63483,202238950011,2022,Emenda Individual - Transferências Especiais,3895.0,ABILIO SANTANA,11,MÚLTIPLO,Sem informação,Múltiplo,2900000,...,TRANSFERENCIAS ESPECIAIS,0,TRANSFERENCIAS ESPECIAIS,4000000.00,3500000.00,3500000.00,500000.00,0.0,500000.00,202238950011
63484,202238950012,2022,Emenda Individual - Transferências com Finalid...,3895.0,ABILIO SANTANA,12,BAHIA (UF),Sem informação,Sem informação,2900000,...,FORTALECIMENTO DO SISTEMA NACIONAL DE VIGILANC...,0,FORTALECIMENTO DO SISTEMA NACIONAL DE VIGILANC...,1071631.00,0.00,0.00,1071631.00,0.0,1071631.00,202238950012
63485,202238960001,2022,Emenda Individual - Transferências com Finalid...,3896.0,ABOU ANNI,1,SÃO PAULO (UF),Sem informação,Sem informação,3500000,...,ESTRUTURACAO DE UNIDADES DE ATENCAO ESPECIALIZ...,0,ESTRUTURACAO DE UNIDADES DE ATENCAO ESPECIALIZ...,811695.00,99962.00,99962.00,711733.00,711733.0,0.00,202238960001
63486,202238960002,2022,Emenda Individual - Transferências Especiais,3896.0,ABOU ANNI,2,MÚLTIPLO,Sem informação,Múltiplo,3500000,...,TRANSFERENCIAS ESPECIAIS,0,TRANSFERENCIAS ESPECIAIS,8800000.00,4400000.00,4400000.00,4400000.00,0.0,4400000.00,202238960002
63487,202238960003,2022,Emenda Individual - Transferências com Finalid...,3896.0,ABOU ANNI,3,MÚLTIPLO,Sem informação,Múltiplo,3500000,...,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,0,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,6517305.00,6517305.00,6517305.00,0.00,0.0,0.00,202238960003
63488,202238960004,2022,Emenda Individual - Transferências com Finalid...,3896.0,ABOU ANNI,4,MÚLTIPLO,Sem informação,Múltiplo,3500000,...,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,0,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,2172435.00,2172435.00,2172435.00,0.00,0.0,0.00,202238960004
63489,202238970001,2022,Emenda Individual - Transferências Especiais,3897.0,ACACIO FAVACHO,1,MÚLTIPLO,Sem informação,Múltiplo,1600000,...,TRANSFERENCIAS ESPECIAIS,0,TRANSFERENCIAS ESPECIAIS,8819682.00,4409841.00,4409841.00,4409841.00,0.0,4409841.00,202238970001
63490,202238970002,2022,Emenda Individual - Transferências com Finalid...,3897.0,ACACIO FAVACHO,2,MÚLTIPLO,Sem informação,Múltiplo,1600000,...,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,0,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,5432050.00,5432050.00,5432050.00,0.00,0.0,0.00,202238970002
63491,202238970003,2022,Emenda Individual - Transferências com Finalid...,3897.0,ACACIO FAVACHO,3,AMAPÁ (UF),Sem informação,Sem informação,1600000,...,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,0,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,4149741.00,4149741.00,4149741.00,0.00,0.0,0.00,202238970003
63492,202226330001,2022,Emenda Individual - Transferências com Finalid...,2633.0,ACIR GURGACZ,1,Nacional,Sem informação,Sem informação,-1,...,APRESTAMENTO DAS FORCAS - MANUTENCAO DA PRONTI...,0,APRESTAMENTO DAS FORCAS - MANUTENCAO DA PRONTI...,249999.67,240235.01,204095.01,45904.66,0.0,45904.66,202226330001
63493,202226330002,2022,Emenda Individual - Transferências com Finalid...,2633.0,ACIR GURGACZ,2,Nacional,Sem informação,Sem informação,-1,...,ASSISTENCIA MEDICA QUALIFICADA E GRATUITA A TO...,0,ASSISTENCIA MEDICA QUALIFICADA E GRATUITA A TO...,108641.00,108641.00,108641.00,0.00,0.0,0.00,202226330002
63494,202226330003,2022,Emenda Individual - Transferências Especiais,2633.0,ACIR GURGACZ,3,CABIXI - RO,1100031,CABIXI,1100000,...,TRANSFERENCIAS ESPECIAIS,0,TRANSFERENCIAS ESPECIAIS,350000.00,0.00,0.00,350000.00,0.0,350000.00,202226330003
63495,202226330004,2022,Emenda Individual - Transferências Especiais,2633.0,ACIR GURGACZ,4,JI-PARANÁ - RO,1100122,JI-PARANÁ,1100000,...,TRANSFERENCIAS ESPECIAIS,0,TRANSFERENCIAS ESPECIAIS,500000.00,0.00,0.00,500000.00,0.0,500000.00,202226330004
63496,202226330005,2022,Emenda Individual - Transferências Especiais,2633.0,ACIR GURGACZ,5,SÃO FELIPE D'OESTE - RO,1101484,SÃO FELIPE D'OESTE,1100000,...,TRANSFERENCIAS ESPECIAIS,0,TRANSFERENCIAS ESPECIAIS,500000.00,0.00,0.00,500000.00,0.0,500000.00,202226330005
63497,202226330006,2022,Emenda Individual - Transferências com Finalid...,2633.0,ACIR GURGACZ,6,MÚLTIPLO,Sem informação,Múltiplo,-14,...,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,0,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,3280613.00,3080613.00,3080613.00,200000.00,0.0,200000.00,202226330006
63498,202226330007,2022,Emenda Individual - Transferências com Finalid...,2633.0,ACIR GURGACZ,7,SÃO PAULO (UF),Sem informação,Sem informação,3500000,...,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,0,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,543205.00,543205.00,543205.00,0.00,0.0,0.00,202226330007
63499,202226330008,2022,Emenda Individual - Transferências com Finalid...,2633.0,ACIR GURGACZ,8,MÚLTIPLO,Sem informação,Múltiplo,1100000,...,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,0,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,3041948.00,2791948.00,2791948.00,250000.00,0.0,250000.00,202226330008
63500,202226330009,2022,Emenda Individual - Transferências com Finalid...,2633.0,ACIR GURGACZ,9,CURITIBA - PR,4106902,CURITIBA,4100000,...,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,0,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,651846.00,651846.00,651846.00,0.00,0.0,0.00,202226330009
63501,202226330010,2022,Emenda Individual - Transferências Especiais,2633.0,ACIR GURGACZ,10,ARIQUEMES - RO,1100023,ARIQUEMES,1100000,...,TRANSFERENCIAS ESPECIAIS,0,TRANSFERENCIAS ESPECIAIS,500000.00,0.00,0.00,500000.00,0.0,500000.00,202226330010
63502,202226330011,2022,Emenda Individual - Transferências Especiais,2633.0,ACIR GURGACZ,11,ALTA FLORESTA D'OESTE - RO,1100015,ALTA FLORESTA D'OESTE,1100000,...,TRANSFERENCIAS ESPECIAIS,0,TRANSFERENCIAS ESPECIAIS,250000.00,0.00,0.00,250000.00,0.0,250000.00,202226330011

Foram registradas 6108 emendas em 2022.

## 2) Filtre as emendas da região **Norte** que tenham `Valor Empenhado` maior que **500.000** e mostre as 5 primeiras linhas. Em seguida, responda: quantas emendas atendem a esses duas condições ao mesmo tempo?

In [ ]:
emendas_norte_alto_valor = df[(df['Região'] == 'Norte') & (df['Valor Empenhado'] > 500000)]
display(emendas_norte_alto_valor.head(5))
num_emendas_norte_alto_valor = len(emendas_norte_alto_valor)
print(f"Foram encontradas {num_emendas_norte_alto_valor} emendas que atendem a ambas as condições.")

,Código da Emenda,Ano da Emenda,Tipo de Emenda,Código do Autor da Emenda,Nome do Autor da Emenda,Número da emenda,Localidade de aplicação do recurso,Código Município IBGE,Município,Código UF IBGE,...,Nome Ação,Código Plano Orçamentário,Nome Plano Orçamentário,Valor Empenhado,Valor Liquidado,Valor Pago,Valor Restos A Pagar Inscritos,Valor Restos A Pagar Cancelados,Valor Restos A Pagar Pagos,Código da Emenda_1
18,Sem informação,2014,Emenda Individual - Transferências com Finalid...,NaN,None,S/I,MÂNCIO LIMA - AC,1200336,MÂNCIO LIMA,1200000,...,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO PR...,0,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO BA...,616610.0,0.0,0.0,0.0,0.0,616610.0,Sem informação
120,Sem informação,2014,Emenda Individual - Transferências com Finalid...,NaN,None,S/I,VITÓRIA DO JARI - AP,1600808,VITÓRIA DO JARI,1600000,...,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO PR...,0,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO BA...,522384.4,0.0,0.0,0.0,0.0,522384.4,Sem informação
160,Sem informação,2014,Emenda Individual - Transferências com Finalid...,NaN,None,S/I,SANTANA - AP,1600600,SANTANA,1600000,...,IMPLEMENTACAO DE INFRAESTRUTURA BASICA NOS MUN...,0,IMPLEMENTACAO DE INFRAESTRUTURA BASICA NOS MUN...,4443000.0,0.0,0.0,0.0,4443000.0,0.0,Sem informação
170,Sem informação,2014,Emenda Individual - Transferências com Finalid...,NaN,None,S/I,PALMEIRAS DO TOCANTINS - TO,1713809,PALMEIRAS DO TOCANTINS,1700000,...,APOIO A POLITICA NACIONAL DE DESENVOLVIMENTO U...,0,APOIO A POLITICA NACIONAL DE DESENVOLVIMENTO U...,935350.0,0.0,0.0,0.0,0.0,935350.0,Sem informação
218,Sem informação,2014,Emenda Individual - Transferências com Finalid...,NaN,None,S/I,COSTA MARQUES - RO,1100080,COSTA MARQUES,1100000,...,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO PR...,0,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO BA...,549995.0,0.0,0.0,0.0,159996.0,389999.0,Sem informação

Foram encontradas 6230 emendas que atendem a ambas as condições.

## 3) Filtre as emendas que são do estado de **SÃO PAULO** ou do estado do **RIO DE JANEIRO** e mostre quantas linhas cada estado possui. Em seguida, responda: Qual dos dois estados possui mais emendas e quantas são?

In [ ]:
df['UF'] = df['Localidade de aplicação do recurso'].str.extract(r' - ([A-Z]{2})$')
uf_to_estado = {
    'SP': 'SÃO PAULO',
    'RJ': 'RIO DE JANEIRO'
}
df['Estado'] = df['UF'].map(uf_to_estado)
df_sp_rj = df[(df['Estado'] == 'SÃO PAULO') | (df['Estado'] == 'RIO DE JANEIRO')]
contagem_por_estado = df_sp_rj['Estado'].value_counts()
print("Contagem de emendas por estado:")
display(contagem_por_estado)
estado_com_mais_emendas = contagem_por_estado.idxmax()
num_emendas_maior_estado = contagem_por_estado.max()
print(f"\nO estado com mais emendas é {estado_com_mais_emendas} com {num_emendas_maior_estado} emendas.")
print("\nPrimeiras 5 linhas do DataFrame filtrado:")
display(df_sp_rj.head())

Contagem de emendas por estado:

Estado
SÃO PAULO         4730
RIO DE JANEIRO    3805
Name: count, dtype: int64

O estado com mais emendas é SÃO PAULO com 4730 emendas.

Primeiras 5 linhas do DataFrame filtrado:

,Código da Emenda,Ano da Emenda,Tipo de Emenda,Código do Autor da Emenda,Nome do Autor da Emenda,Número da emenda,Localidade de aplicação do recurso,Código Município IBGE,Município,Código UF IBGE,...,Código Plano Orçamentário,Nome Plano Orçamentário,Valor Empenhado,Valor Liquidado,Valor Pago,Valor Restos A Pagar Inscritos,Valor Restos A Pagar Cancelados,Valor Restos A Pagar Pagos,Código da Emenda_1,Estado
3,Sem informação,2014,Emenda Individual - Transferências com Finalid...,NaN,None,S/I,ARARAQUARA - SP,3503208,ARARAQUARA,3500000,...,0,APOIO A PROJETOS DE INFRAESTRUTURA TURISTICA -...,243750.0,0.0,0.0,0.0,243750.0,0.0,Sem informação,SÃO PAULO
16,Sem informação,2014,Emenda Individual - Transferências com Finalid...,NaN,None,S/I,ITALVA - RJ,3302056,ITALVA,3300000,...,0,INFRAESTRUTURA PARA A EDUCACAO BASICA - DESPES...,343000.0,0.0,0.0,0.0,343000.0,0.0,Sem informação,RIO DE JANEIRO
20,Sem informação,2014,Emenda Individual - Transferências com Finalid...,NaN,None,S/I,PILAR DO SUL - SP,3537909,PILAR DO SUL,3500000,...,0,APOIO A POLITICA NACIONAL DE DESENVOLVIMENTO U...,245850.0,0.0,0.0,0.0,0.0,245850.0,Sem informação,SÃO PAULO
30,Sem informação,2014,Emenda Individual - Transferências com Finalid...,NaN,None,S/I,VALENÇA - RJ,3306107,VALENÇA,3300000,...,0,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO BA...,1399800.0,0.0,0.0,0.0,0.0,1399800.0,Sem informação,RIO DE JANEIRO
37,Sem informação,2014,Emenda Individual - Transferências com Finalid...,NaN,None,S/I,MONTE ALTO - SP,3531308,MONTE ALTO,3500000,...,0,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO BA...,248757.0,0.0,0.0,0.0,0.0,248757.0,Sem informação,SÃO PAULO

## 4) Na coluna `Código da Emenda`, substitua todos os valores `"Sem informação"` por `"Não disponível"`. Mostre a contagem de valores únicos da coluna antes e depois da substituição.

In [ ]:
df['Código da Emenda'] = df ['Código da Emenda'].replace("Sem informação" , "Não disponível")
print(df['Código da Emenda'].value_counts())

Código da Emenda
Não disponível    17808
202341820007          2
202336610004          2
201833870003          2
201833870004          2
                  ...
201921520003          1
201921520002          1
201921520001          1
201930530018          1
201921520008          1
Name: count, Length: 70731, dtype: int64

## 5) Na coluna `Nome Função`, transforme todos os valores para que fiquem em letras maiúsculas. Confirme a alteração mostrando os valores únicos da coluna.

In [ ]:
df['Nome Função'] = df['Nome Função'].str.upper()
print(df['Nome Função'].unique())

['URBANISMO' 'COMÉRCIO E SERVIÇOS' 'SAÚDE' 'EDUCAÇÃO' 'AGRICULTURA'
 'ASSISTÊNCIA SOCIAL' 'DESPORTO E LAZER' 'DEFESA NACIONAL' 'SANEAMENTO'
 'DIREITOS DA CIDADANIA' 'GESTÃO AMBIENTAL' 'CULTURA'
 'CIÊNCIA E TECNOLOGIA' 'SEGURANÇA PÚBLICA' 'ORGANIZAÇÃO AGRÁRIA'
 'COMUNICAÇÕES' 'ADMINISTRAÇÃO' 'HABITAÇÃO' 'INDÚSTRIA' 'TRABALHO'
 'MÚLTIPLO' 'TRANSPORTE' 'PREVIDÊNCIA SOCIAL' 'ENCARGOS ESPECIAIS'
 'RELAÇÕES EXTERIORES' 'ENERGIA' 'ESSENCIAL À JUSTIÇA']

## 6) Verifique quantas linhas duplicadas existem no dataset. Em seguida, remova as duplicatas e mostre quantas linhas sobraram.

In [ ]:
print(df.duplicated().sum())
df = df.drop_duplicates()
print(df.duplicated().sum())

63
0

## 7) Remova duplicatas considerando apenas as colunas `Código da Emenda` e `Município`. Quantas linhas sobraram? O resultado é diferente de quando removemos duplicatas do DataFrame inteiro?

In [ ]:
df_novo=df.drop_duplicates(subset=['Código da Emenda', 'Município'])
df_novo.ssape[0]

## 8) Identifique quais colunas possuem valores nulos e quantos nulos cada uma tem. Em seguida, responda: qual é a coluna que possui maior número de valores nulos e quantos são?

In [ ]:
df_nulos = df.isnull().sum()
print(df_nulos)

Código da Emenda                          0
Ano da Emenda                             0
Tipo de Emenda                            0
Código do Autor da Emenda                 0
Nome do Autor da Emenda                   0
Número da emenda                          0
Localidade de aplicação do recurso        0
Código Município IBGE                     0
Município                                 0
Código UF IBGE                            0
UF                                    51618
Região                                    0
Código Função                             0
Nome Função                               0
Código Subfunção                          0
Nome Subfunção                            0
Código Programa                           0
Nome Programa                             0
Código Ação                               0
Nome Ação                                 0
Código Plano Orçamentário                 0
Nome Plano Orçamentário                   0
Valor Empenhado                           0
Valor Liquidado                           0
Valor Pago                                0
Valor Restos A Pagar Inscritos            0
Valor Restos A Pagar Cancelados           0
Valor Restos A Pagar Pagos                0
Código da Emenda_1                        0
Estado                                80083
dtype: int64

## 9) Preencha os valores nulos da coluna `codigo do autor` com **-1** e os valores nulos da coluna `nome do autor da emenda` com "desconhecido" e confirme que não restaram nulos nessa coluna.

In [ ]:
df['Código do Autor da Emenda'] = df['Código do Autor da Emenda'].fillna(-1)
df['Nome do Autor da Emenda'] = df['Nome do Autor da Emenda'].fillna("Desconhecido")

/tmp/ipykernel_3445/3914700483.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Código do Autor da Emenda'] = df['Código do Autor da Emenda'].fillna(-1)
/tmp/ipykernel_3445/3914700483.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Nome do Autor da Emenda'] = df['Nome do Autor da Emenda'].fillna("Desconhecido")

## 10) Verifique o tipo da coluna `Ano da Emenda`. Converta-a para **string** (`str`). Mostre o tipo antes e depois da conversão.

In [ ]:
df['Ano da Emenda'] = df['Ano da Emenda'].astype(str)

/tmp/ipykernel_3445/4174900545.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Ano da Emenda'] = df['Ano da Emenda'].astype(str)

## 11) Converta a coluna `Valor Empenhado` para o tipo **float** (caso ainda não seja). Mostre o tipo após a conversão.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 88596 entries, 0 to 88595
Data columns (total 30 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Código da Emenda                    88596 non-null  object
 1   Ano da Emenda                       88596 non-null  object
 2   Tipo de Emenda                      88596 non-null  object
 3   Código do Autor da Emenda           88596 non-null  float64
 4   Nome do Autor da Emenda             88596 non-null  object
 5   Número da emenda                    88596 non-null  object
 6   Localidade de aplicação do recurso  88596 non-null  object
 7   Código Município IBGE               88596 non-null  object
 8   Município                           88596 non-null  object
 9   Código UF IBGE                      88596 non-null  int64
 10  UF                                  36978 non-null  object
 11  Região                              88596 non-null  object
 12  Código Função                       88596 non-null  object
 13  Nome Função                         88596 non-null  object
 14  Código Subfunção                    88596 non-null  object
 15  Nome Subfunção                      88596 non-null  object
 16  Código Programa                     88596 non-null  object
 17  Nome Programa                       88596 non-null  object
 18  Código Ação                         88596 non-null  object
 19  Nome Ação                           88596 non-null  object
 20  Código Plano Orçamentário           88596 non-null  object
 21  Nome Plano Orçamentário             88596 non-null  object
 22  Valor Empenhado                     88596 non-null  float64
 23  Valor Liquidado                     88596 non-null  float64
 24  Valor Pago                          88596 non-null  float64
 25  Valor Restos A Pagar Inscritos      88596 non-null  float64
 26  Valor Restos A Pagar Cancelados     88596 non-null  float64
 27  Valor Restos A Pagar Pagos          88596 non-null  float64
 28  Código da Emenda_1                  88596 non-null  object
 29  Estado                              8513 non-null   object
dtypes: float64(7), int64(1), object(22)
memory usage: 21.0+ MB

## 12) Calcule o **total** de `Valor Pago` por **Região**. Quais são as duas regiões que mais receberam recursos?

In [ ]:
df_regiao = df.groupby('Região')['Valor Pago'].sum()
df_regiao

Região
Centro-Oeste    1.037094e+10
Exterior        2.572317e+07
Múltiplo        3.010563e+10
Nacional        7.885927e+09
Nordeste        4.644279e+10
Norte           2.034243e+10
Sudeste         3.426218e+10
Sul             1.648147e+10
Name: Valor Pago, dtype: float64

## 13) Calcule a **quantidade** de emendas por **Nome Função**. Mostre as 5 funções com mais emendas.

In [ ]:
em_nome_func = df.groupby('Nome Função')['Código da Emenda'].count().sort_values(ascending=False)
em_nome_func.head()

Nome Função
SAÚDE                 37039
URBANISMO              8655
EDUCAÇÃO               8101
AGRICULTURA            4938
ENCARGOS ESPECIAIS     4610
Name: Código da Emenda, dtype: int64

## 14) Crie uma nova coluna chamada `Saldo a Pagar`. Ela deve ser o resultado da subtração entre a coluna `Valor Empenhado` e a coluna `Valor Pago`. Mostre as 5 primeiras linhas apenas com essas três colunas.

In [ ]:
df['Saldo a Pagar'] = df['Valor Empenhado'] - df['Valor Pago']
df['Saldo a Pagar'].head()

/tmp/ipykernel_3445/3261944343.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Saldo a Pagar'] = df['Valor Empenhado'] - df['Valor Pago']

0     700000.00
1     487500.00
2     100000.00
3     243750.00
4    1658333.94
Name: Saldo a Pagar, dtype: float64

## 15) Elimine a(s) coluna(s) do dataframe que eestá totalmente vazia.

In [ ]:
df = df.drop(columns = ['Código da Emenda_1'])

## 16) Para finalizar, salve o DataFrame transformado em um arquivo no formato JSON.

In [1]:
df.to_json('df_transformado.json' , index = False)

NameError: name 'df' is not defined